// <auto-generated />
namespace CLMTB.Infrastructure.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCorre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCorre));
        
        string IMigrationMetadata.Id
        {
            get { return "201604120334306_AddCorre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
